### ISSUE TITLE
Scriptassist check gets confused when minor revision number has two digits

### ISSUE THREAD

**Issue by Vilkku** [irssi/scripts.irssi.org#125]
So, just learnt about scriptassist and ran /scriptassist check. This surprised me:

    | o cap_sasl       Your version is newer (1.5->1.1)

When investigating, I found that the version for cap_sasl is set to 1.10 in this repo. If you treat version numbers as floats I understand what scriptassist is getting at, but version numbers are not floats, so the result in this case is incorrect - 1.10 is a newer version than 1.5. However, it seems like more complex version numbers (such as screen_away 0.9.8.1) do not cause any problems, so I might be wrong with my assumption that the issue is comparing version numbers as floats.

In addition, as I mentioned, the latest cap_sasl version is 1.10, but scriptassist and the website reports it as being 1.1.

**Comment by ailin-nemui** [comment]
Thanks for your investigation, I believe this is due to the version numbers correctly getting extracted from the script (where they are not floats) and stored into an intermediate YAML file (also not as floats) but they are unfortunately not quoted. The page rendering step takes the input from this YAML file and interprets everything as float that looks like a float, i.e. 1.10 is affected but 0.9.8 is not because the latter couldn't legally be treated as a float value.
