### ISSUE TITLE
[sysinfo277-irssi.pl] Illegal division by zero at line 408.

### ISSUE THREAD

**Issue by 0xicl33n** [irssi/scripts.irssi.org#356]
I have no idea what has happened to my sysinfo. It was literally working fine yesterday. Now i get this error. I redownloaded it and replaced the existing one with the download and i still get the same error

Heres what line 408 looks like..

` $varp = sprintf("%.2f", $vard / $vara * 100);`

And heres my perl.

This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-thread-multi

**Comment by dequis** [comment]
Bunch of conditions in that function, hard to tell which one fails. Maybe the output of sysinfo itself would help narrow it down.

Workaround, change this 1 to 0, around line 140 of the script

```
my $showMemoryUsage	= 1;
```

**Comment by 0xicl33n** [comment]
That worked!

**Comment by dequis** [comment]
Yeah but now you don't have memory usage. Not sure if you want to keep digging into this to fix it - but i'd do something like adding lines like this one:

```
Irssi::print(1);
```

Right under each $vara line, increasing the 1 for each print you add.

Otherwise if you don't want to deal with this and are fine with hiding memory usage, we can close this.

**Comment by ailin-nemui** [comment]
check if @bw1 fixed it in the latest upload?

**Comment by bw1** [comment]
I don't think it's liable to happen.
